server:
    port: 8787

spring:
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: ENC(V7uxaUx7c/nB0jbDj09kKJXw2Zm6ho7Mhsb5EXvO8N4=)
        password: ENC(e07I3QPBo5RYqFX/dKyry4cFCtQog3/5kZ5mXZYAw4I=)
        default-encoding: UTF-8
        protocol: smtp
        properties:
            mail.smtp:
                auth: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000
                starttls.enable: true
    security:
        oauth2:
            client:
                authorization:
                    clients: # 클라이언트 정보를 설정하는 부분
                        admin-client:
                            client-id: admin-client-id
                            client-secret: admin-client-secret
                            scope: openid, profile, email # 클라이언트가 요청할 수 있는 범위
                            authorization-grant-type: authorization_code # 인증 방식
                            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}' # 리다이렉트 URI
                registration:
                    google:
                        client-id: ENC(vwTGZKqcNMGUGkRzbGbrF663PbXAVJyuSvArG80gmZh1HnAy9/5fSkxEtE2VTPLV6GS2+e1NOlmxnbKyv2FoukVzzD2psCM1xBKS/qjQGz3g6LcGzGjXPA==)
                        client-secret: ENC(OKfUrp0aOUDXDfi7AuhQp/xvIw3gTMCbue9tuv4plh73hxYSgIHbJ79MyDKD/Rz5)
                        scope: openid, profile, email, address, phone
                        redirect-uri: '{baseUrl}/login/oauth2/code/google'
                        client-name: Google
                    naver:
                        client-id: your-naver-client-id
                        client-secret: your-naver-client-secret
                        scope: profile, email
                        redirect-uri: '{baseUrl}/login/oauth2/code/naver'
                        client-name: Naver
                    kakao:
                        client-id: your-kakao-client-id
                        client-secret: your-kakao-client-secret
                        scope: profile, email
                        redirect-uri: '{baseUrl}/login/oauth2/code/kakao'
                        client-name: Kakao
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
mail:
    from: oozu1994@gmail.com
    base-url: https://localhost:8443
    forgot-password:
        subject: Account Recovery - OUR-ALL-WEBTOON
        template-name: content/mail/forgotPasswordTemplate
    account-verify:
        subject: Account Verify - OUR-ALL-WEBTOON
        template-name: content/mail/accountVerifyTemplate

logging:
    config: classpath:logback/logback-local.xml

mongo:
    username: ENC(rfCjq/fvgGJZIBPu4TF1C9E0qEboaAQg)
    password: ENC(bdOwFie/fMdXq22I+5P6Xtmi0LchCGfB8YdmW1xcJ7A=)
    url: ENC(qFsTPlFDy9Q1WKskaXThpoEiicMouV1dv0TN/F8aQLvJnG1apISJq/TIFaTX6Xm5NWX8udGOZVXlg23o5wmgzvcZkFE2KibOJ2UDApFDhIsRThxFW+hcA5NxG/eqLMb+Je30AQtq/ZY=)

password:
    encoder:
        secret: ENC(sYNRJmMaXB8X/TyGKHmOJy+SgsBhReEJvUEtu/My9HBokenNUx69i1DW5EHOYLphyfRdvC4Q3KpCIc0Fvg/xMa66JkKUZp29mviOpF9IqPI/RFEqTobHfVdoEobP1wlG)
        iteration: 50
        keylength: 256

key:
    jwt:
        file:
            dir:
        public:
            name: our-all-webtoon-jwt.pub
            s3-key: ENC(ERGBt5XmyiJA+MATTj8t4wsx6cxwvi7eDkQaUvFxVctB2644ZJN3B+kgkaU6wPVBmUZWjbNtGdiw8HKk1xqzM+gPwJIExgnEI/PpPLRg51V8uAOdIc9379A3KB1jhp5QZ6SU9fx4OXG4B0ujNpAIxDjnSa90VpYm)
            s3-slat: ENC(l1LxE4XLD8rnfnB0mcX6Mhf/mlkA4+eAdPAtVH8jGPuSwTV1Dki9PH7yXnQQvW9kNFQ/1vHnsfAVNi4LjJKqliZyjzszwlwXwRuoPkqUL2Y=)
        private:
            name: our-all-webtoon-jwt.key
            s3-key: ENC(i7WDPxmANFgPhx3oeQvUDTtEBLRQYIB+SpYsz0sCLxZtKAvpIiTzzu9WPUky2zYi6OOde4K9ZdMAV1cfowJ+vbrkX45634/H9C6HETvRfrjh6cJqinIxeMGy+cZiXzVGKagYIUDhLnQ9oFJ5w+A3N/j7HbeYu1EW)
            s3-slat: ENC(dA9UOEWNcCcEThYCZxahYV+Jm3wh4yO23Yofalf5J7ftKOL1PKiYpvkkYjyS8tJDsJUqUvO3zM1zv+43DWmm4fnf4EiQryljfx7kN6FZLSE=)
    privacy:
        file:
            dir:
        public:
            name: our-all-webtoon-privacy.pub
            s3-key: ENC(47udyzMO4UG8Lk0YOYT3/F+IlD+MZtNfGCuym8GcbGXMIiZHQKZ1C+sWF2room+lT4WSs6EPl93Y0O61MTuS4HElxFAbQHMVUHEq64Yye6lh20n2r2ndhYCyPtw+5HOfkSVpmNfewdoNd84NczSQIzmPHnqgOrw/)
            s3-slat: ENC(3LJlPphLPYZK1caGa7FTJ8RpJJbOuWuKJ7SN8z9kUgGfRqqT2QNoyNlPoL2NMolyUiITDnyjr4mfXtIQ3TZb0AuOPwMTyZp6q7I6OL5p2cA=)
        private:
            name: our-all-webtoon-privacy.key
            s3-key: ENC(h3eMSmJtYm+Ko0tRwF2foghtbMwSRE/y00RX5d0hJQDVeQyxlEfz18yKk01I6VJfC4+f2XPFAWTNZ/HgnYQ6izidd2YAPO7A1P8gxTCB0X4vgP94wtHY/DA+TZ7fcc75Qu8VwyjwiriRHFj4CXjHXOzBx+4DSeoa)
            s3-slat: ENC(dWpEaG/7MyeueMNbwRGta1XuQe27T74bWpoURMi48hRrJyGIKr/weNgOoxTQ6hPlT/M5mXbreJDsJ0LmKRA0JFWXyD1bMrZ980o/iG21jtk=)

s3:
    access-key: ENC(5pj5D+soHZATHUGjaDc7p3Uuc8DNi1bdv75hYfEVa9Q=)
    security-key: ENC(zxDmKLw+mL++w/Dlh9FDeG3KdAr75jNw4mZAy+1uj1O9HzELyb1cFnpZ8rNEISoDbmY8l9FDwUg=)
    region: ap-northeast-2
    bucket: bird-plus-s3
    bucket-public: bird-plus-s3-public
    key:
        account: account
# OAuth2 클라이언트 설정
